name: Build Release APK
on:
  workflow_dispatch:
    inputs:
      variant:
        description: 'Build Variant to assemble'
        required: true
        default: 'assembleLawnWithQuickstepNightlyRelease'
        type: choice
        options:
          - assembleLawnWithQuickstepNightlyRelease
          - assembleLawnWithQuickstepGithubRelease
          - assembleLawnWithQuickstepPlayRelease
          - assembleLawnWithQuickstepGithubDebug

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-encryption-key: Da25KUVSE5jbGds2zXmfXw==
      - name: Build APK
        run: ./gradlew ${{ github.event.inputs.variant || 'assembleLawnWithQuickstepNightlyRelease' }} --stacktrace
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Lawnchair-${{ github.event.inputs.variant || 'Release' }}
          path: |
            build/outputs/**/*.apk
            lawnchair/build/outputs/**/*.apk
          if-no-files-found: warn

